### ISSUE TITLE
None of the buttons are clickable.

### ISSUE THREAD

**Issue by PixsaOJ** [FineFuturity/FrameUIForFirefox#2]
I just upgraded from Firefox 121 to Firefox 123.

I can only click window control buttons. All the other buttons are unclickable.

**Comment by AlNexus** [comment]
I have the same issue, the buttons are only clickable once I enable "Title Bar" in the Customize Toolbar page.

**Comment by FineFuturity** [comment]
Just made a small tweak to the userChrome.css file on main and appears to fix it for me.  Hopefully it works for you too, please test and let me know what happens.  :)

**Comment by FineFuturity** [comment]
Just discovered the titlebar buttons are no longer clickable after my small tweak🤦 sorry this has taken so long, been a busy week on my end.  I'll dig into this more when i get home tonight.

**Comment by PixsaOJ** [comment]
> Just discovered the titlebar buttons are no longer clickable after my small tweak🤦 sorry this has taken so long, been a busy week on my end. I'll dig into this more when i get home tonight.

Its okay, you don't owe us anything 🥇

**Comment by PixsaOJ** [comment]
Original issue was fixed, I'm going to keep using this theme. who needs close/min/max buttons anyways

**Comment by FineFuturity** [comment]
I know this is closed, but just wanted to update and let you know that I fixed it.  You should be able to click on all of the buttons in the nav-bar as well as the window controls.

Give the new version a test and let me know if it works for you. :)

**Comment by PixsaOJ** [comment]
I'm not able to test it at the moment. Is it okay if I close the issue if it works for you?
