### ISSUE TITLE
Just in case you're unaware

### ISSUE THREAD

**Issue by Manueljlin** [FineFuturity/FrameUIForFirefox#5]
Smartisan, a Chinese hardware and software company that somehow got acquihired by TikTok, made an Android based deviced called the Smartisan TNT, which had the same philosophy of bridging the gap between mobile devices and desktops (also through the use of bottom title bars)

**Comment by FineFuturity** [comment]
Oh, that's interesting!  I'll take a look and see how it is.  Thanks :)
